version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: acorn
    versions:
    - 8.0.5
    - 8.1.0
    - 8.1.1
